require: rubocop-rails

Layout/LineLength:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/ExplicitBlockArgument:
  Enabled: false
Rails/Validation:
  Enabled: false
